version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "deps(py)"
      prefix-development: "deps(py-dev)"
    cooldown:
      default-days: 5
      semver-major-days: 30
      semver-minor-days: 7
      semver-patch-days: 3
    groups:
      production-dependencies:
        dependency-type: "production"
      development-dependencies:
        dependency-type: "development"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "deps(gha)/"
    groups:
      github-actions:
        patterns:
          - "*"
  - package-ecosystem: "npm"
    directory: "web/pingpong/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "deps(web)"
      prefix-development: "deps(web-dev)"
    ignore:
      - dependency-name: "flowbite-svelte"
        update-types: ["version-update:semver-major", "version-update:semver-minor", "version-update:semver-patch"]
      - dependency-name: "svelte"
        update-types: ["version-update:semver-major"]
      - dependency-name: "tailwindcss"
        update-types: ["version-update:semver-major"]
      - dependency-name: "eslint"
        update-types: ["version-update:semver-major"]
    cooldown:
      default-days: 5
      semver-major-days: 30
      semver-minor-days: 7
      semver-patch-days: 3
    groups:
      production-dependencies:
        dependency-type: "production"
      development-dependencies:
        dependency-type: "development"
  - package-ecosystem: "npm"
    directory: "web/study/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "deps(study)"
      prefix-development: "deps(study-dev)"
    cooldown:
      default-days: 5
      semver-major-days: 30
      semver-minor-days: 7
      semver-patch-days: 3
    groups:
      production-dependencies:
        dependency-type: "production"
      development-dependencies:
        dependency-type: "development"
