[tool.poetry]
name = "pingpong"
version = "2.3.4"
description = "A software platform carefully designed for AI-driven learning."
authors = ["Joe Nudell <jnudell@hks.harvard.edu>", "Evangelos Kassos <github@evangeloskassos.com>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.10"
openai = {extras = ["realtime"], version = "^2.8.0"}
pydantic = "^2.3.0"
pydantic-settings = "^2.0.3"
slack-sdk = "^3.21.3"
sentry-sdk = "^2.8.0"
aiocontextvars = "^0.2.2"
tiktoken = "^0.5.1"
async-throttle = "1.0.0"
opentelemetry-api = "^1.20.0"
requests = "^2.32.4"
fastapi = {extras = ["standard"], version = "^0.120.1"}
starlette = ">=0.49.1"
uvicorn = "0.31.0"
aiohttp = "^3.12.14"
sqlalchemy = {extras = ["asyncio"], version = "^2.0.43"}
pyjwt = "^2.8.0"
aiosqlite = "^0.19.0"
python-multipart = "^0.0.18"
websockets = "^13.0"
azure-communication-email = "^1.0.0"
aiosmtplib = "^3.0.1"
asyncpg = "^0.29.0"
alembic = "^1.13.1"
psycopg2-binary = "^2.9.9"
discord-py = "^2.3.2"
openfga-sdk = "0.7"
uvloop = "^0.19.0"
opentelemetry-sdk = "^1.23.0"
pytz = "^2024.1"
httpx = "0.27.0"
httpcore = "1.0.9"
anyio = "4.3.0"
gunicorn = "^23.0.0"
orjson = "^3.9.15"
mmh3 = "4.1.0"
python-glowplug = "^0.3.12"
python3-saml = "^1.16.0"
arrow = "^1.3.0"
humanize = "^4.10.0"
aioboto3 = "^13.1.1"
uvicorn-worker = "^0.2.0"
email-validator = "^2.2.0"
beautifulsoup4 = "^4.13.4"
pydub = "^0.25.1"
pybase64 = "^1.4.1"
uuid-utils = "^0.11.0"
pyairtable = "^3.1.1"

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.2"
pre-commit = "^3.4.0"
locust = "^2.20.0"
pytest-asyncio = "^0.23.5"
tqdm = "^4.66.3"

[tool.poetry.group.local-scripts-qualtrics]
optional = true

[tool.poetry.group.local-scripts-qualtrics.dependencies]
selenium = "^4.30.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
