[tool.poetry]
name = "aitutor"
version = "0.1.0"
description = ""
authors = ["Joe Nudell <jnu@stanford.edu>"]
readme = "README.md"


[tool.poetry.dependencies]
python = "^3.10"
openai = "^0.28.0"
pydantic = "^2.3.0"
pydantic-settings = "^2.0.3"
slack-sdk = "^3.21.3"
sentry-sdk = "^1.30.0"
aiocontextvars = "^0.2.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
