log_level = "DEBUG"
public_url = "http://localhost:5173"
development = true

[artifact_store]
type = "local"
save_target = "/path/to/test"

[file_store]
type = "local"
save_target = "/path/to/test"

[db]
engine = "sqlite"
path = "test_db.sqlite"

[auth]

[[auth.authn_methods]]
method = "sso"
protocol = "saml"
provider = "harvardkey"
name = "Harvard"
domains = ["harvard.edu", "*.harvard.edu"]
excluded_domains = ["alumni.harvard.edu", "post.harvard.edu"]

[[auth.authn_methods]]
method = "magic_link"
name = "Email"
expiry = 86400

[[auth.secret_keys]]
key = "test env secret key for hs256 tests"

[email]
type = "mock"

[authz]
type = "openfga"
scheme = "http"
host = "localhost"
port = "11800"
store = "pingpong"
cfg = "./pingpong/authz/authz.fga.json"
key = "devkey"

[[lms.lms_instances]]
type = "canvas"
tenant = "demo"
tenant_friendly_name = "Demo Institution"
sso_tenant = "demo"
sso_target = "key"
base_url = "http://canvas.docker"
client_id = "your client id here"
client_secret = "your client secret here"
sync_wait = 600
auth_token_expiry = 3600
