log_level = "DEBUG"
public_url = "http://localhost:5173"
canvas_url = "http://canvas.docker"
canvas_client_id = "10000000000001"
canvas_client_secret = "7D7UREveNZrzfNxBGRvQyf4mh4P4JVT7Mxk8U6VJeDayEY6uXc9vC3khYHCHm9cE"
development = true

[db]
engine = "sqlite"
path = "test_db.sqlite"

[auth]

[[auth.authn_methods]]
method = "sso"
protocol = "saml"
provider = "harvardkey"
name = "Harvard"
domains = ["harvard.edu", "*.harvard.edu"]
excluded_domains = ["alumni.harvard.edu", "post.harvard.edu"]

[[auth.authn_methods]]
method = "magic_link"
name = "Email"
expiry = 86400

[[auth.secret_keys]]
key = "test env"

[email]
type = "mock"

[authz]
type = "openfga"
scheme = "http"
host = "localhost"
port = "11800"
store = "pingpong"
cfg = "./pingpong/authz/authz.fga.json"
key = "devkey"
