log_level = "DEBUG"
public_url = "http://localhost:5173"
development = true

[db]
engine = "sqlite"
path = "test_db.sqlite"

[auth]

[[auth.authn_methods]]
method = "magic_link"
name = "Other"
expiry = 86400

[[auth.secret_keys]]
key = "test env"

[email]
type = "mock"

[authz]
type = "openfga"
scheme = "http"
host = "localhost"
port = "11800"
store = "pingpong"
cfg = "./pingpong/authz/authz.fga.json"
key = "devkey"
