team_id = "T05LR6BUJM7" # API 201 C&D
variables = { focus = "statistics using R and tidyverse" }
[[models]]
name = "api-201-cd-general"
[[models]]
name = "api-201-cd-quiz"
[[models]]
name = "api-201-cd-search"
