[workspace]
team_id = "T05LR6BUJM7" # API 201 C&D
variables = { focus = "statistics using R and tidyverse" }
[[workspace.models]]
name = "general"
[[workspace.models]]
name = "quiz"
[[workspace.models]]
name = "api-201-*"
[workspace.models.params]
index_name = "api-201-cd"
