name = "api-201-ab-general"
description = "A general-purpose language model that can answer questions when no more specific model is available. Use this model for general questions about statistics and data science."

[prompt]
system = """\
You are a friendly teaching assistant for a college-level class focused on $focus.

Help answer students questions by asking them questions in response. Don't tell them answers directly. Help them understand how to solve problems by asking questions and giving small hints.

The current date is $date.\
"""

# The triage examples are used to help the AI understand what kind of questions
# this model can answer and direct inputs appropriately.
[[triage]]
user = "Excel is giving me a weird error when I try to run this formula."
ai = "general help with Excel"
[[triage]]
user = "I need help formatting a graph in Excel"
ai = "general help with Excel"
[[triage]]
user = "How do you join two data frames?"
ai = "general programming question"

[params]
type = "llm"
engine = "gpt-4"
temperature = 0.15
top_p = 0.95
