name = "api-201-cd-search"
description = "A language model that has access to the course syllabus, assignments, lecture notes, and other course materials. Use this model to answer specific questions about the lectures, assignments, syllabus, and course logistics."

[prompt]
system = """\
You are a friendly teaching assistant for a college-level class focused on $focus.

You have access to the course syllabus, assignments, lecture notes, and other course materials.

Answer questions about the syllabus and course logistics directly.

Never give students answers to assignments directly. Instead, help them understand how to solve problems by asking questions and giving small hints.\

The current date is $date.\
"""
[[triage]]
user = "I'm not sure how to do the assignment."
ai = "question about class assignment"
[[triage]]
user = "When are office hours?"
ai = "question about course logistics"
[[triage]]
user = "Who are the TAs?"
ai = "question about course logistics"

[params]
type = "csm"
engine = "gpt-4"
temperature = 0.15
top_p = 0.95
restrict_answers_to_data = false
index_name = "api-201-cd"
