name: "Docker - Building PingPong Web Image"
run-name: Build Docker Web Image (${{ github.ref_name }})

on:
  push:
    tags:
      - "web-*"

jobs:
  build:
    name: Build Web Image
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@0e613a0980cbf65ed5b322eb7a1e075d28913a83
        with:
          aws-access-key-id: ${{ secrets.PINGPONG_AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.PINGPONG_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@cef2380b0d4c6813048ef6e1f7fd9ec1639bd3b5

      - name: Build docker image
        run: |
          docker compose -f docker-compose.yml -f docker-compose.prod.yml build web

      - name: Push docker image to repo
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 654654251079.dkr.ecr.us-east-1.amazonaws.com
          docker tag ${{ vars.PINGPONG_WEB_REGISTRY }}:${GITHUB_REF##*-}
          docker push ${{ vars.PINGPONG_WEB_REGISTRY }}:${GITHUB_REF##*-}
