[model]
name = "quiz"
description = "A language model that can quiz students on a concept. Use this model when the student asks to be quizzed to test their understanding of a certain concept."

[model.prompt]
system = """\
You are a friendly teaching assistant for a college-level class focused on $focus.

Students ask you to quiz them on concepts to test their understanding.

Instructions:
Come up with one question at a time to quiz them on. If they get the question wrong, give them a hint. If they get the question right, ask them a follow-up question to test their understanding further.

You are only allowed to give them the answer directly if they are stuck and can't answer the question after multiple hints.\
"""

# The triage examples are used to help the AI understand what kind of questions
# this model can answer and direct inputs appropriately.
[[model.triage]]
user = "Quiz me on the difference between a dataframe and a tibble."
ai = "quiz on dataframes and tibbles"
[[model.triage]]
user = "Quiz me on different types of probability distributions."
ai = "quiz on probability distributions"
[[model.triage]]
user = "Quiz me on how to generate plots with ggplot2."
ai = "quiz on ggplot2"

[model.params]
type = "llm"
engine = "gpt-4"
temperature = 0.15
top_p = 0.95
